# Generated by Django 4.2.7 on 2023-12-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_description_alter_game_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='game_photos/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_year',
            field=models.IntegerField(),
        ),
    ]
