# Generated by Django 4.2.7 on 2023-12-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_item_description_item_release_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Game',
        ),
    ]
